template = '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubernetes
  name: kubernetes
spec:
  serviceAccount: kubernetes
  containers:
  - image: buginets/mycommand:1.0.0
    name: kubernetes

'''

podTemplate(cloud: 'kubernetes', label: 'kubernetes', yaml: template) {
node ("kubernetes") {
    container ("kubernetes") {
    stage ("Checkout SCM") {
        git branch: 'main', url: 'https://github.com/buginets/jenkins-february-2025.git'
      }

    stage ("test"){
        sh  """
        terraform version
        kubectl version
        helm version
        kubectl get nodes
        """
    }  
      }
    }
    }